# Usar una imagen de Node.js como base
FROM node:16
# Crear el directorio de trabajo en el contenedor
WORKDIR /app
# Copiar package.json y package-lock.json para instalar dependencias
COPY package*.json ./
# Instalar dependencias
RUN npm install
# Copiar el resto del código fuente de la aplicación
COPY . .
# Compilar la aplicación NestJS
RUN npm run build
# Exponer el puerto en el que corre la aplicación (por defecto
3000 en NestJS)
EXPOSE 3000
# Comando para iniciar la aplicación
CMD ["npm", "run", "start:prod"]