version: "3"
services:
  app:
    build:
      # La carpeta actual
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapea el puerto de la app a localhost
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      # Conexión a MongoDB en el contenedor
      - MONGO_URI=mongodb://mongo:27017/nestdb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      # Base de datos predeterminada
      MONGO_INITDB_DATABASE: nestdb
